charity_user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


# form for creating a new charity
class NewCharityPage(FlaskForm):
    name = StringField(validators=[DataRequired()])
    description = TextAreaField(validators=[DataRequired()])
    submit = SubmitField()


# form for changing name
class NameForm(FlaskForm):
    name = StringField(validators=[DataRequired()])
    submit = SubmitField()

admin/views.py
# IMPORTS
import logging

from flask_login import login_required, current_user
from flask import Blueprint, render_template, request
from sqlalchemy import asc

from admin.forms import RolesForm
from app import db, requires_roles
from models import User

# CONFIG
admin_blueprint = Blueprint('admin', __name__, template_folder='templates')


# VIEWS
# view admin homepage
@admin_blueprint.route('/admin', methods=['GET', 'POST'])
@login_required
@requires_roles('admin')
def admin():
    form = RolesForm()
    if form.validate_on_submit():
        # updates the role of a user with inputted email
        User.query.filter_by(email=form.email.data).update({"roleID": form.role.data})
        db.session.commit()
        # adds information about role change to the log
        logging.warning('SECURITY - Privilege Modification [%s, %s, %s, %s]', current_user.email, form.email.data, form.role.data, request.remote_addr)
    with open("charity_forum.log", "r") as f:  # open log file for reading
        content = f.read().splitlines()[-10:]  # read the last ten lines
        content.reverse()  # reverse them into order
    users = User.query.order_by(asc('username')).all()
    return render_template('admin.html', users=users, form=form, logs=content)

charity/views.py
import copy
from datetime import datetime

from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required
from geopy import distance

from app import db, requires_roles
from charity.forms import PostForm, SearchForm, NewEventForm, TagForm, DescriptionForm, NameForm, CommentForm, \
    FollowForm
from models import Page, Comment, User, Post, Tag, Event


# Blueprints
charity_blueprint = Blueprint("charity", __name__, template_folder="templates")


# VIEWS
# view for charity's homepage
@charity_blueprint.route('/<int:id>/page', methods=['GET', 'POST'])
def page(id):
    charity_page = Page.query.get(id)
    form = FollowForm()
    if form.validate_on_submit():
        # adds user to charity's followers
        charity_page.followers.remove(current_user) if current_user in charity_page.followers \
            else charity_page.followers.append(current_user)
        db.session.commit()

    events = Event.query.filter_by(page_id=charity_page.id).all()
    return render_template('charity_page.html', form=form, posts=charity_page.posts, page=charity_page,
                           add_tag_form=TagForm(), remove_tag_form=TagForm(), events=events,
                           change_desc_form=DescriptionForm(), change_name_form=NameForm())


# view for post creation page
@charity_blueprint.route('/<int:page_id>/create', methods=('GET', 'POST'))
@login_required
@requires_roles('charity')
def create(page_id):
    form = PostForm()

    if form.validate_on_submit():

        # creates a new post with the inputted data
        time = datetime.now()
        new_post = Post(title=form.title.data, content=form.content.data, page_id=page_id,
                        time_created=time)

        # adds the new post to the database
        db.session.add(new_post)
        db.session.commit()

        return redirect(url_for("charity.page", id=page_id))
    return render_template('create.html', form=form)


# view for post update page
@charity_blueprint.route('/<int:id>/update', methods=('GET', 'POST'))
@login_required
@requires_roles('charity')
def update(id):
    post = Post.query.filter_by(id=id).first()
    if not post:
        return render_template('500.html')
    form = PostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data

        db.session.commit()

        return redirect(url_for("charity.page", id=post.page_id))

    # creates a copy of post object which is independent of database.
    post_copy = copy.deepcopy(post)

    # set update form with title and body of copied post object
    form.title.data = post_copy.title
    form.content.data = post_copy.content

    return render_template('update.html', form=form)


# deletes a post
@charity_blueprint.route('/<int:id>/delete')
@login_required
@requires_roles('charity')
def delete(id):
    post = Post.query.filter_by(id=id).first()
    page_id = post.page_id
    Post.query.filter_by(id=id).delete()
    db.session.commit()

    return redirect(url_for("charity.page", id=page_id))


# view for individual posts
@charity_blueprint.route('/<int:id>/view', methods=('GET', 'POST'))
def view(id):
    post = Post.query.filter_by(id=id).first()
    form = CommentForm()
    comments = Comment.query.filter_by(post=post.id, original=None)
    users = User.query.all()
    if form.validate_on_submit():
        # creates a new comment with the inputted data
        new_comment = Comment(
            commentor_id=current_user.id,
            post=post.id,
            text=form.text.data,
            original=int(form.reply_to.data) if form.reply_to.data != "" else None
        )
        # adds the comment to the database
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for("charity.view", id=post.id, post=post, form=form, comments=Comment.walk(comments), users=users ))

    return render_template('post.html', post=post, form=form, comments=Comment.walk(comments), users=users)


# returns json list of all events within a certain distance of the coords
@charity_blueprint.route('/<string:coords>/<int:threshold>/nearby')
def nearby(coords, threshold):
    lat, lon = map(float, coords.split(":"))
    events = list(filter(lambda event: distance.distance((event.lat, event.lon), (lat, lon)).miles < threshold,
                         Event.query.all()))
    return {"events": list(
        map(lambda event: {"id": event.id, "name": event.name, "lat": event.lat, "lon": event.lon}, events))}


# Takes user search query, searches for a charity with a matching name, and charities with matching tags.
@charity_blueprint.route('/search', methods=["GET", "POST"])
def search():
    # Create search form
    form = SearchForm()
    # Initialise list of results
    results = []

    # If request method is POST or form is valid
    if form.validate_on_submit():
        # Removes whitespace at the beginning and end of search query
        search_text = form.search.data.strip()

        # Query database for charities with a matching username
        charity = Page.query.filter_by(name=search_text).first()
        # split search text into individual words

        words = search_text.split(" ")
        # Initialise list of tags
        search_tags = []
        for word in words:
            for tag in Tag.query.filter_by(subject=word).all():
                # If a word in the search query matches an existing tag, then add the tag to the list
                search_tags.append(tag)

        # Get list of charities with tags matching those in the list
        charities = []
        for tag in search_tags:
            for tag_page in tag.pages:
                charities.append(tag_page)

        # Create final list of results
        results = list(filter(lambda x: x is not None, [charity] + charities))

    return render_template('search.html', form=form, results=results)


# adds a charity tag based on inputted data
@charity_blueprint.route("/<int:page_id>/tag", methods=["POST"])
@login_required
@requires_roles("charity")
def add_tag(page_id):
    form = TagForm()

    if form.validate_on_submit:
        tag = Tag.query.filter_by(subject=form.subject.data).first()
        if not tag:
            tag = Tag(subject=form.subject.data)
            db.session.add(tag)
            db.session.commit()
        current_page = Page.query.get(page_id)
        current_page.tags.append(tag)
        db.session.commit()

    return redirect(url_for("charity.page", id=page_id))


# removes a charity tag based on inputted data
@charity_blueprint.route("/<int:page_id>/removetag", methods=["POST"])
@login_required
@requires_roles("charity")
def remove_tag(page_id):
    form = TagForm()

    if form.validate_on_submit:
        tag = Tag.query.filter_by(subject=form.subject.data).first()
        current_page = Page.query.get(page_id)
        current_page.tags.remove(tag)
        db.session.commit()

    return redirect(url_for("charity.page", id=page_id))


# changes charity's description based on inputted data
@charity_blueprint.route("/<int:page_id>/change_desc", methods=["POST"])
@login_required
@requires_roles("charity")
def change_desc(page_id):
    form = DescriptionForm()
    if form.validate_on_submit:
        Page.query.update({"description": form.description.data})
        db.session.commit()

    return redirect(url_for("charity.page", id=page_id))


# changes charity's name based on inputted data
@charity_blueprint.route("/<int:page_id>/change_name", methods=["POST"])
@login_required
@requires_roles("charity")
def change_name(page_id):
    form = NameForm()
    if form.validate_on_submit:
        Page.query.update({"name": form.name.data})
        db.session.commit()

    return redirect(url_for("charity.page", id=page_id))


@charity_blueprint.route('/<int:page_id>/new_event', methods=['GET', 'POST'])
@login_required
@requires_roles('charity')
def new_event(page_id):
    form = NewEventForm()
    if form.validate_on_submit():
        # create a new event from inputted data
        newevent = Event(page=page_id,
                         name=form.name.data,
                         description=form.description.data,
                         time=form.time.data,
                         date=form.date.data,
                         lat=form.lat.data,
                         lon=form.lon.data,
                         )
        # add the new user to the database
        db.session.add(newevent)
        db.session.commit()

        return redirect(url_for("charity.page", id=page_id))
    return render_template('event.html', form=form)


# deletes an event
@charity_blueprint.route('/<int:id>/delete_event')
@login_required
@requires_roles('charity')
def delete_event(id):
    event = Event.query.filter_by(id=id).first()
    page_id = event.page_id
    Event.query.filter_by(id=id).delete()
    db.session.commit()

    return redirect(url_for("charity.page", id=page_id))


#view event
@charity_blueprint.route('/<int:id>/view_event')
def view_event(id):
    event = Event.query.filter_by(id=id).first()
    return render_template('view_event.html', event=event)

charity_user/views.py
# IMPORTS

from flask_login import login_required, current_user
from flask import Blueprint, render_template, flash, url_for, redirect

from app import db, requires_roles
from models import Page, User

# CONFIG
from charity_user.forms import NewCharityPage, NameForm

charity_user_blueprint = Blueprint('charity_user', __name__, template_folder='templates')


# VIEWS
# view charity profile
@charity_user_blueprint.route('/charity_profile', methods=['GET', 'POST'])
@login_required
@requires_roles('charity')
def charity_profile():
    return render_template('charity_user.html', pages=current_user.pages, change_name_form=NameForm(), following=current_user.followed_pages)


@charity_user_blueprint.route('/newcharity', methods=['GET', 'POST'])
@login_required
@requires_roles('charity')
def new_charity():
    form = NewCharityPage()
    if form.validate_on_submit():
        page = Page.query.filter_by(name=form.name.data).first()
        # if this returns a page, then the name already exists in database

        # if name already exists redirect user back to new charity page with error message so user can try again
        if page:
            flash('Charity with this name already exists')
            return render_template("new_charity.html", form=form)

        # create a new page with the form data
        new_charity = Page(name=form.name.data,
                           description=form.description.data,
                           user_id=current_user.id,
                           )

        # add the new page to the database
        db.session.add(new_charity)
        db.session.commit()
        return charity_profile()

    return render_template('new_charity.html', form=form)


@charity_user_blueprint.route("/change_name", methods=["POST"])
@login_required
@requires_roles("charity")
def change_name():
    form = NameForm()
    if form.validate_on_submit:
        User.query.filter_by(id=current_user.id).update({"username": form.name.data})
        db.session.commit()

    return redirect(url_for("charity_user.charity_profile"))

templates/admin.html
{% extends "base.html" %}

{% block content %}
    <div class="tab">
        <button class="tablink" onclick="tabView('Profile')" id="default">Profile</button>
        <button class="tablink" onclick="tabView('AllUsers')">All Users</button>
        <button class="tablink" onclick="tabView('Logs')">Logs</button>

        <div id="Profile" class="tabcontent">
            <h3> {{ current_user.username }} </h3>
        </div>

        <div id="AllUsers" class="tabcontent">
        <div class="column is-5 is-offset-4">
        <div class="box">
            <form method="POST">
                <h2 class="title">Change User's Role</h2>
                <div class="field">
                    {{ form.hidden_tag() }}
                    <div class="control">
                        {{ form.email(class="input", placeholder="Email") }}
                    </div>
                    <div class="error">
                        {% for error in form.email.errors %}
                            {{ error }}
                        {% endfor %}

                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.role(class="dropdown", placeholder="New Role") }}
                    </div>
                    <div class="error">
                        {% for error in form.role.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>

            <div class="box" id="allUsers">
                <div class="row" id="topUserRow">
                    <div class="column" id="userColumn">
                        <h2>Name</h2>
                    </div>
                    <div class="column" id="userColumn">
                        <h2>Email</h2>
                    </div>
                    <div class="column" id="userColumn">
                        <h2>Role</h2>
                    </div>
                </div>
                {% for user in users %}
                    <div class="row" id="userRow">
                        <div class="column" id="userColumn">
                            <p>{{ user.username }}</p>
                        </div>
                        <div class="column" id="userColumn">
                            <p>{{ user.email }}</p>
                        </div>
                        <div class="column" id="userColumn">
                            <p>{{ user.roleID }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div id="Logs" class="tabcontent">
            <h3> Logs </h3>
            {% for log in logs %}
            <p>{{ log }}</p>
            {% endfor %}
        </div>
    </div>
    <script>
        document.getElementById("default").click();
    </script>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Charity Website</title>
    <link rel="stylesheet" href="{{ url_for("static", filename="main.css") }}" type="text/css"/>
    <script src="{{ url_for("static", filename="script.js") }}">
    </script>
</head>

<body>


<section class="hero is-primary is-fullheight">
    <div class="hero-head">
        <nav class="navbar">
            <div class="container">
                <div id="navbarMenuHeroA" class="navbar-menu">
                    <div class="navbar-end">
                        <a href="javascript:void(0);" class="icon" onclick="responsiveNav()">&#9776;</a>
                        <a href="{{ url_for('index') }}" class="navbar-item">
                            Main Page
                        </a>
                        <a href="{{ url_for('explore') }}" class="navbar-item">
                            Explore
                        </a>
                        <a href="{{ url_for('map') }}" class="navbar-item">
                            Map
                        </a>
                        <a href="{{ url_for('charity.search') }}" class="navbar-item">
                            Search
                        </a>
                        {% if current_user.is_authenticated and current_user.roleID=='charity' %}
                            <a href="{{ url_for('charity_user.charity_profile') }}" class="navbar-item">
                                Profile
                            </a>
                        {% endif %}
                        {% if current_user.is_authenticated and current_user.roleID=='admin' %}
                            <a href="{{ url_for('admin.admin') }}" class="navbar-item">
                                Admin
                            </a>
                        {% endif %}
                        {% if current_user.is_authenticated and current_user.roleID=='user' %}
                            <a href="{{ url_for('user.profile') }}" class="navbar-item">
                                Profile
                            </a>
                        {% endif %}
                        {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.register') }}" class="navbar-item">
                                Sign Up
                            </a>
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                        {% else %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Log out
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <div class="hero-body">
        <div class="container has-text-centered">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</section>


</body>
<footer>
    <p>Contact Us: <a href="mailto:charity.ly@email.com">charity.ly@email.com</a></p>
  <p>Authors:  Kalina Hajzner, Simon M. Horrocks, Joseph Burley, Joe Ireland </p>

</footer>
</html>

templates/charity_page.html
{% extends "base.html" %}

{% block content %}

    <h1 class="title is-1">{{ page.name }}</h1>

    <div class="tab">
        <button class="tablink" onclick="tabView('Profile')" id="default">Profile</button>
        <button class="tablink" onclick="tabView('Posts')">Posts</button>
        <button class="tablink" onclick="tabView('Events')">Events</button>
        {% if current_user.id == page.user_id %}
            <button class="tablink" onclick="tabView('Settings')">Settings</button>
        {% endif %}
        <div id="Profile" class="tabcontent">
            <h3>              {{ page.name }} </h3>
            <p>{{ page.description }}</p>
            <form method="POST">
                <div class="field">
                    {{ form.hidden_tag() }}
                <div class="follow">
                    {% if page in current_user.followed_pages %}
                        {{ form.submit(class="button3", value="Unfollow") }}
                    {% else %}
                        {{ form.submit(class="button3", value="Follow") }}
                    {% endif %}
                </div>

            </form>
                </div>
            {% if page in current_user.pages %}
                <a href="{{ url_for('charity.create', page_id=page.id) }}" class="button2">
                    <button>New Post</button>
                </a>
                <a href="{{ url_for('charity.new_event', page_id=page.id) }}" class="button2">
                    <button>New Event</button>
                </a>
            {% endif %}

        </div>


        <div id="Posts" class="tabcontent">
            <h3> Posts </h3>
            <div class="box">
                {% for post in posts %}
                    <article class="media">
                        <div class="media-content">
                            <div class="content">
                                <h4>
                                    <a href="{{ url_for('charity.view', name=post.page_id, id=post.id) }}">{{ post.title }}</a>
                                </h4>
                                <p>
                                    <strong>{{ post.parent_page.name }}</strong>
                                    <small>{{ post.time_created.strftime('%d-%m-%Y %H:%M') }}</small>
                                    <br>
                                    {{ post.content }}
                                    <br>
                                    {% if page in current_user.pages %}
                                        <div id="post-navbar" class="navbar-menu">
                                            <div class="navbar-start">
                                                <a class="navbar-item" id="update-navbar"
                                                   href="{{ url_for('charity.update', id=post.id) }}">Update</a>
                                                <a class="navbar-item" id="update-navbar"
                                                   href="{{ url_for('charity.delete', id=post.id) }}">Delete</a>
                                            </div>
                                        </div>
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    </article>
                {% endfor %}
            </div>
        </div>
        <div id="Events" class="tabcontent">
            <h3> Events </h3>
            <div class="box">
                {% for event in events %}
                    <article class="media">
                        <div class="media-content">
                            <div class="content">
                                <h4>{{ event.name }}</h4>
                                <p>
                                    <strong>{{ event.event_page.name }}</strong>
                                    <small>{{ event.date.strftime('%d-%m-%Y') }}</small>
                                    <small>{{ event.time.strftime('%H:%M') }}</small>
                                    <small>{{ event.lat, event.lon }}</small>
                                    <br>
                                    {{ event.description }}
                                    <br>
                                    {% if page in current_user.pages %}
                                        <div id="post-navbar" class="navbar-menu">
                                            <div class="navbar-start">
                                                <a class="navbar-item" id="update-navbar"
                                                   href="{{ url_for('charity.delete_event', id=event.id) }}">Delete</a>
                                            </div>
                                        </div>
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    </article>
                {% endfor %}
            </div>
        </div>
        {% if current_user.id == page.user_id %}
            <div id="Settings" class="tabcontent">
                <h3> Settings </h3>
                <h3>Name</h3>
                <p>{{ page.name }}</p>
                <h5>Change Name</h5>
                <form method="POST" action="{{ url_for('charity.change_name', page_id=page.id) }}">
                    {{ change_name_form.hidden_tag() }}
                    {{ change_name_form.name() }}
                    {{ change_name_form.submit() }}
                </form>
                <h3>Description</h3>
                <p>{{ page.description }}</p>
                <h5>Change Description</h5>
                <form method="POST" action="{{ url_for('charity.change_desc', page_id=page.id) }}">
                    {{ change_desc_form.hidden_tag() }}
                    {{ change_desc_form.description() }}
                    {{ change_desc_form.submit() }}
                </form>
                <h3> Tags </h3>
                {% for tag in page.tags %}
                    <p>{{ tag.subject }}</p>
                {% endfor %}
                <h5> Add Tags </h5>
                <form method="POST" action="{{ url_for('charity.add_tag', page_id=page.id) }}">
                    {{ add_tag_form.hidden_tag() }}
                    {{ add_tag_form.subject() }}
                    {{ add_tag_form.submit() }}
                </form>
                <h5> Remove Tags </h5>
                <form method="POST" action="{{ url_for('charity.remove_tag', page_id=page.id) }}">
                    {{ remove_tag_form.hidden_tag() }}
                    {{ remove_tag_form.subject() }}
                    {{ remove_tag_form.submit() }}
                </form>
            </div>
            </div>
        {% endif %}
    <script>
        document.getElementById("default").click();
    </script>
{% endblock %}

templates/charity_user.html
{% extends "base.html" %}

{% block content %}

    <h1 class="title is-1">Profile</h1>

    <div class="tab">
        <button class="tablink" onclick="tabView('Profile')" id="default">Profile</button>
        <button class="tablink" onclick="tabView('Following')">Following</button>
        <button class="tablink" onclick="tabView('MyCharities')">My Charities</button>
        <button class="tablink" onclick="tabView('Settings')">Settings</button>

        <div id="Profile" class="tabcontent">
            <h3> {{ current_user.username }} </h3>
        </div>
     <div id="Following" class="tabcontent">
            <h3> Following </h3>
                {% for following in following %}
                    <p><a href="{{ url_for('charity.page', id=following.id) }}" id="following">{{ following.name }}</a></p>
                {% endfor %}
        </div>
        <div id="MyCharities" class="tabcontent">
            <h3> My Charities </h3>
            {% if pages %}
                <div class="content">
                    {% for page in pages %}
                    <p><a href="{{ url_for('charity.page', id=page.id)}}" , id="mycharities">
                    {{ page.name }}
                    </a></p>
                    {% endfor %}
                </div>
            {% endif %}
            <a href="{{ url_for('charity_user.new_charity') }}" class="button2">
                <button>New Charity</button>
            </a>
            {% for charity in charities %}
                <a href="{{ url_for('charity.blog', name=charity.name) }}">{{ charity.name }}</a>
            {% endfor %}
        </div>
        <div id="Settings" class="tabcontent">
            <h3> Settings </h3>
            <h3>Username</h3>
                <p>{{ current_user.username }}</p>
                <h5>Change Username</h5>
                <form method="POST" action="{{ url_for('charity_user.change_name') }}">
                    {{ change_name_form.hidden_tag() }}
                    {{ change_name_form.name() }}
                    {{ change_name_form.submit() }}
                </form>
        </div>

    </div>
<script>
    document.getElementById("default").click();
</script>
{% endblock %}

templates/charityuser.html
{% extends "base.html" %}

{% block content %}

    <h1 class="title is-1">Profile</h1>

    <div class="tab">
        <button class="tablink" onclick="tabView('Profile')" id="default">Profile</button>
        <button class="tablink" onclick="tabView('MyCharities')">My Charities</button>
        <button class="tablink" onclick="tabView('Settings')">Settings</button>

        <div id="Profile" class="tabcontent">
            <h3> Profile </h3>
        </div>
        <div id="MyCharities" class="tabcontent">
            <h3> My Charities </h3>
            <a href="{{ url_for('charity_user.newCharity') }}" class="button2">
                <button>New Charity</button>
            </a>
            {% for charity in charities %}
                <a href="{{ url_for('charity.blog', name=charity.name) }}">{{ charity.name }}</a>
            {% endfor %}
        </div>
        <div id="Settings" class="tabcontent">
            <h3> Settings </h3>
        </div>

    </div>
<script>
    document.getElementById("default").click();
</script>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

    <h1 class="title is-1">Charit.ly</h1>
    <article>
        <p id="introduction">
            Charit.ly is a platform designed to bring charities and supporters together from the team at Sigma Industries
            who are dedicated to supporting the UN's goals on collaboration. Follow the charities you care about and get
            involved!
        </p>
    </article>
{% if posts %}
<div class="box">
<h2>Posts</h2>
    {% for post in posts %}
    <article class="media">
        <div class="media-content">
            <div class="content">
                <h4>
                    <a href="{{ url_for('charity.view', id=post.id) }}">{{ post.title }}</a>
                </h4>
                <p>
                    <strong><a href="{{ url_for( 'charity.page', id=post.page_id) }}" id="pageName">{{ post.parent_page.name }}</a></strong>
                    <small>{{ post.time_created.strftime('%d-%m-%Y %H:%M') }}</small>
                    <br>
                    {{ post.content }}
                    <br>
                    {% if page in current_user.pages %}
                        <div id="post-navbar" class="navbar-menu">
                            <div class="navbar-start">
                                <a class="navbar-item"
                                   href="{{ url_for('charity.update', id=post.id) }}">Update</a>
                                <a class="navbar-item"
                                   href="{{ url_for('charity.delete', id=post.id) }}">Delete</a>
                            </div>
                        </div>
                    {% endif %}
            </div>
        </div>
    </article>
    {% endfor %}
</div>
{% endif %}


{% endblock %}